routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes([
    'register' => false
]);

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/profile', [DashboardController::class, 'profile'])->name('profile');
    Route::post('/profile/{user:id}/update', [DashboardController::class, 'update'])->name('profile.update');
    Route::resource('users', UserController::class)->middleware('isadmin');
    Route::get('/nilai', [SiswaController::class, 'nilai'])->name('nilai.index')->middleware('isadmin');
    Route::get('/siswa/reset/{siswa:id}', [SiswaController::class, 'reset'])->name('siswa.reset')->middleware('isadmin');
    Route::resource('siswa', SiswaController::class)->middleware('isadmin');
    Route::post('/question/answer', [QuestionController::class, 'answer'])->name('question.answer');
    Route::get('/question/find/{question:id}', [QuestionController::class, 'find'])->name('question.find');
    Route::resource('question', QuestionController::class);
});

Route::get('/install', function () {
    shell_exec('composer install');
    shell_exec('cp .env.example .env');
    Artisan::call('key:generate');
    Artisan::call('migrate:fresh --seed');
    Artisan::call('cache:clear');
});

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function siswa()
    {
        return $this->belongsToMany(Siswa::class)->withPivot('deskripsi', 'jawaban', 'nilai');
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Question;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class QuestionController extends Controller
{

    public function __construct()
    {
        $this->middleware('isadmin')->except('show', 'find', 'answer');
    }

    public function index()
    {
        $questions = Question::get();

        return view('question.index', compact('questions'));
    }

    public function create()
    {
        $question = new Question();

        return view('question.create', compact('question'));
    }

    public function store(Request $request)
    {
        $attr = $request->validate([
            'nama' => 'required',
            'soal' => 'required',
            'jawaban' => 'required',
            'batas_atas' => 'required',
            'batas_bawah' => 'required',
            'bobot_nilai' => 'required',
        ]);

        try {
            DB::beginTransaction();

            Question::create($attr);

            DB::commit();

            return redirect()->route('question.index')->with('success', 'Soal berhasil ditambahkan');
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->with('error', $th->getMessage());
        }
    }

    public function show(Question $question)
    {
        return view('question.show', compact('question'));
    }

    public function edit(Question $question)
    {
        return view('question.edit', compact('question'));
    }

    public function update(Request $request, Question $question)
    {
        $attr = $request->validate([
            'nama' => 'required',
            'soal' => 'required',
            'jawaban' => 'required',
            'batas_atas' => 'required',
            'batas_bawah' => 'required',
            'bobot_nilai' => 'required',
        ]);

        try {
            DB::beginTransaction();

            $question->update($attr);

            DB::commit();

            return redirect()->route('question.index')->with('success', 'Soal berhasil diupdate');
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->with('error', $th->getMessage());
        }
    }

    public function destroy(Question $question)
    {
        try {
            DB::beginTransaction();

            $question->siswa()->detach();
            $question->delete();

            DB::commit();

            return redirect()->route('question.index')->with('success', 'Soal berhasil didelete');
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->with('error', $th->getMessage());
        }
    }

    public function find(Question $question)
    {
        return response()->json([
            'question' => $question
        ]);
    }

    public function answer(Request $request)
    {
        $request->validate(
            [
                'deskripsi' => 'required',
                'jawaban' => 'required',
            ],
            [
                'deskripsi.required' => 'Deskripsi harus di isi',
                'jawaban.required' => 'Jawaban harus di isi',
            ]
        );
        try {
            $question = Question::find($request->question_id);

            $data = ['deskripsi' => $request->deskripsi, 'jawaban' => $request->jawaban, 'nilai' => $request->nilai];

            $question->siswa()->attach($request->siswa_id, $data);

            return redirect()->route('dashboard')->with('success', 'Soal telah dijawab');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }
}

resources/views/question/create.blade.php
@extends('layouts.master', ['title' => 'Tambah soal'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary card-outline">
            <div class="card-body">
                <form action="{{ route('question.store') }}" method="post">
                    @csrf

                    @include('question.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')

@endpush

resources/views/question/edit.blade.php
@extends('layouts.master', ['title' => 'Edit Soal'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary card-outline">
            <div class="card-body">
                <form action="{{ route('question.update', $question->id) }}" method="post">
                    @method('PATCH')
                    @csrf

                    @include('question.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')

@endpush

resources/views/question/form.blade.php
<div class="form-group">
    <label for="nama">Nama Soal</label>
    <input type="text" name="nama" id="nama" class="form-control" value="{{ $question->nama ?? old('nama') }}">

    @error('nama')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label for="soal">Soal</label>
    <textarea name="soal" id="soal" rows="3" class="form-control">{{ $question->soal ?? old('soal') }}</textarea>

    @error('soal')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label for="jawaban">Jawaban</label>
    <input type="text" name="jawaban" id="jawaban" class="form-control" value="{{ $question->jawaban ?? old('jawaban') }}">

    @error('jawaban')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label for="batas_atas">Batas Atas</label>
    <input type="number" name="batas_atas" id="batas_atas" class="form-control" value="{{ $question->batas_atas ?? old('batas_atas') }}">

    @error('batas_atas')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label for="batas_bawah">Batas Bawah</label>
    <input type="number" name="batas_bawah" id="batas_bawah" class="form-control" value="{{ $question->batas_bawah ?? old('batas_bawah') }}">

    @error('batas_bawah')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label for="bobot_nilai">Bobot Nilai</label>
    <input type="number" name="bobot_nilai" id="bobot_nilai" class="form-control" value="{{ $question->bobot_nilai ?? old('bobot_nilai') }}">

    @error('bobot_nilai')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <button type="submit" class="btn btn-primary">Submit</button>
</div>

resources/views/question/index.blade.php
@extends('layouts.master', ['title' => 'Data Soal'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary card-outline">
            <div class="card-body">
                <a href="{{ route('question.create') }}" class="btn btn-primary mb-3">Tambah Soal</a>

                <div class="table-responsive">
                    <table class="table table-bordered table-striped" id="data-table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Soal</th>
                                <th>Batas Atas</th>
                                <th>Batas Bawah</th>
                                <th>Jawaban</th>
                                <th>Bobot</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($questions as $question)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $question->nama }}</td>
                                <td>{{ $question->soal }}</td>
                                <td>{{ $question->batas_atas }}</td>
                                <td>{{ $question->batas_bawah }}</td>
                                <td>{{ $question->jawaban }}</td>
                                <td>{{ $question->bobot_nilai }}</td>
                                <td>
                                    <a href="{{ route('question.edit', $question->id) }}" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>

                                    <form action="{{ route('question.destroy', $question->id) }}" method="post" class="d-inline">
                                        @method('DELETE')
                                        @csrf

                                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Hapus data Admin ?')"><i class="fas fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<script>
    $(document).ready(function() {
        $("#data-table").DataTable()
    })
</script>
@endpush

resources/views/question/show.blade.php
@extends('layouts.master', ['title' => 'Detail Soal'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary card-outline">
            <div class="card-body">
                <h5 class="mb-3">{{ $question->nama }}</h5>

                <p class="card-text">
                    {{ $question->soal }}
                </p>

                <form action="" method="post" id="form-question">
                    @csrf

                    <input type="hidden" name="siswa_id" value="{{ auth()->user()->siswa->id }}">
                    <input type="hidden" name="question_id" value="{{ $question->id }}">
                    <input type="hidden" name="nilai" id="nilai" value="0">

                    <div class="form-group">
                        <label for="deskripsi">Deskripsi Jawaban</label>
                        <textarea name="deskripsi" id="deskripsi" rows="3" class="form-control">{{ old('deskripsi') }}</textarea>

                        @error('deskripsi')
                        <small class="text-danger">{{ $message }}</small>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="jawaban">Jawaban</label>
                        <input type="text" name="jawaban" id="jawaban" class="form-control" value="{{ old('jawaban') }}">

                        @error('jawaban')
                        <small class="text-danger">{{ $message }}</small>
                        @enderror
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-form" disabled>Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    $("#form-question").on("keypress", function(event) {
        var keyPressed = event.keyCode || event.which;
        if (keyPressed === 13) {
            event.preventDefault();
            return false;
        }
    });

    $("#jawaban").on('keyup', function() {
        $(".btn-form").attr('disabled', 'disabled');

        let qid = "{{ $question->id }}";
        let jawaban = $(this).val();

        $.ajax({
            url: "/question/find/" + qid,
            type: 'GET',
            success: function(response) {
                let question = response.question;

                if (jawaban <= question.batas_atas && jawaban >= question.batas_bawah) {
                    $("#form-question").attr('action', '{{ route("question.answer") }}')
                    $(".btn-form").removeAttr(`disabled`);
                }

                if (jawaban == question.jawaban) {
                    $("#nilai").val(question.bobot_nilai)
                } else {
                    $("#nilai").val(0)
                }
            }
        })
    })
</script>
@endpush