routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes([
    'register' => false
]);

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/profile', [DashboardController::class, 'profile'])->name('profile');
    Route::post('/profile/{user:id}/update', [DashboardController::class, 'update'])->name('profile.update');
    Route::resource('users', UserController::class)->middleware('isadmin');
    Route::get('/nilai', [SiswaController::class, 'nilai'])->name('nilai.index')->middleware('isadmin');
    Route::get('/siswa/reset/{siswa:id}', [SiswaController::class, 'reset'])->name('siswa.reset')->middleware('isadmin');
    Route::resource('siswa', SiswaController::class)->middleware('isadmin');
    Route::post('/question/answer', [QuestionController::class, 'answer'])->name('question.answer');
    Route::get('/question/find/{question:id}', [QuestionController::class, 'find'])->name('question.find');
    Route::resource('question', QuestionController::class);
});

Route::get('/install', function () {
    shell_exec('composer install');
    shell_exec('cp .env.example .env');
    Artisan::call('key:generate');
    Artisan::call('migrate:fresh --seed');
    Artisan::call('cache:clear');
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Question;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    public function index()
    {
        $questions = Question::get();

        return view('dashboard.index', compact('questions'));
    }

    public function profile()
    {
        $user = User::find(auth()->user()->id);

        return view('dashboard.profile', compact('user'));
    }

    public function update(User $user, Request $request)
    {
        $attr = $request->validate([
            'username' => 'required|unique:users,username,' . $user->id,
            'name' => 'required',
        ]);

        try {
            DB::beginTransaction();
            $attr['password'] = $request->password != NULL ? bcrypt($request->password) : $user->password;

            if ($user->level == 'Admin') {
                $user->update($attr);
            } else {
                $user->update($attr);

                $user->siswa->update([
                    'nis' => $request->username,
                    'nama' => $request->name,
                    'kelas' => $request->kelas,
                ]);
            }

            DB::commit();

            return back()->with('success', 'Profile berhasil diupdate');
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->with('error', $th->getMessage());
        }
    }
}

resources/views/dashboard/index.blade.php
@extends('layouts.master', ['title' => 'Dashboard'])

@section('content')
@if(auth()->user()->level == 'Admin')
<div class="row">
    <div class="col-lg-4 col-6">
        <div class="small-box bg-danger">
            <div class="inner">
                <h3>{{ App\Models\User::where('level', 'Admin')->count() }}</h3>

                <p>Jumlah Admin</p>
            </div>
            <div class="icon">
                <i class="fas fa-user-shield"></i>
            </div>
            <a href="{{ route('users.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>

    <div class="col-lg-4 col-6">
        <div class="small-box bg-info">
            <div class="inner">
                <h3>{{ App\Models\Siswa::count() }}</h3>

                <p>Jumlah Siswa</p>
            </div>
            <div class="icon">
                <i class="fas fa-users"></i>
            </div>
            <a href="{{ route('siswa.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>

    <div class="col-lg-4 col-6">
        <div class="small-box bg-success">
            <div class="inner">
                <h3>{{ App\Models\Question::count() }}</h3>

                <p>Jumlah Soal</p>
            </div>
            <div class="icon">
                <i class="fas fa-question-circle"></i>
            </div>
            <a href="{{ route('question.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
</div>
@else
<p>
<h5>Aturan Soal</h5>
1. Selesaikan setiap soal untuk membuka soal berikutnya. <br>
2. Anda hanya diperbolehkan menjawab satu kali. <br>
3. Jika terjadi kesalahan, mintalah admin/guru untuk mereset soal.

</p>
<div class="row">
    @foreach($questions as $question)
    <div class="col-md-4">
        <div class="card card-primary card-outline">
            <div class="card-body">
                <h5 class="mb-3">{{ $question->nama }}</h5>

                @if(in_array(auth()->user()->siswa->id, $question->siswa()->pluck('siswa_id')->toArray()))
                <p>
                    <b>Jawaban : </b> {{ $question->siswa[0]->pivot->jawaban }} <br>
                    <b>Nilai : </b> {{ $question->siswa[0]->pivot->nilai }} <br>
                </p>
                @else
                <a href="{{ route('question.show', $question->id) }}" class="btn btn-primary">Kerjakan</a>
                @endif
            </div>
        </div>
    </div>
    @endforeach
</div>
@endif
@stop

resources/views/dashboard/profile.blade.php
@extends('layouts.master', ['title' => 'Profile'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary card-outline">
            <div class="card-body">
                <form action="{{ route('profile.update', $user->id) }}" method="post">
                    @csrf

                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" name="username" id="username" class="form-control" value="{{ $user->username }}">

                        @error('username')
                        <small class="text-danger">{{ $message }}</small>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" id="name" class="form-control" value="{{ $user->name ?? old('name') }}">

                        @error('name')
                        <small class="text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" id="password" class="form-control" value="">

                        @error('password')
                        <small class="text-danger">{{ $message }}</small>
                        @enderror
                    </div>

                    @if(auth()->user()->level == 'Siswa')
                    <div class="form-group">
                        <label for="kelas">Kelas</label>
                        <input type="kelas" name="kelas" id="kelas" class="form-control" value="{{ $user->siswa->kelas }}">

                        @error('kelas')
                        <small class="text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                    @endif
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>
@stop