routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes([
    'register' => false
]);

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/profile', [DashboardController::class, 'profile'])->name('profile');
    Route::post('/profile/{user:id}/update', [DashboardController::class, 'update'])->name('profile.update');
    Route::resource('users', UserController::class)->middleware('isadmin');
    Route::get('/nilai', [SiswaController::class, 'nilai'])->name('nilai.index')->middleware('isadmin');
    Route::get('/siswa/reset/{siswa:id}', [SiswaController::class, 'reset'])->name('siswa.reset')->middleware('isadmin');
    Route::resource('siswa', SiswaController::class)->middleware('isadmin');
    Route::post('/question/answer', [QuestionController::class, 'answer'])->name('question.answer');
    Route::get('/question/find/{question:id}', [QuestionController::class, 'find'])->name('question.find');
    Route::resource('question', QuestionController::class);
});

Route::get('/install', function () {
    shell_exec('composer install');
    shell_exec('cp .env.example .env');
    Artisan::call('key:generate');
    Artisan::call('migrate:fresh --seed');
    Artisan::call('cache:clear');
});

app/Models/Siswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function questions()
    {
        return $this->belongsToMany(Question::class)->withPivot('deskripsi', 'jawaban', 'nilai');
    }
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Siswa;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class SiswaController extends Controller
{
    public function index()
    {
        $siswa = Siswa::get();

        return view('siswa.index', compact('siswa'));
    }

    public function create()
    {
        $siswa = new Siswa();

        return view('siswa.create', compact('siswa'));
    }

    public function store(Request $request)
    {
        $attr = $request->validate([
            'nis' => 'required|unique:siswas',
            'nama' => 'required',
            'kelas' => 'required'
        ]);

        try {
            DB::beginTransaction();

            $user = User::create([
                'username' => $request->nis,
                'name' => $request->nama,
                'password' => bcrypt($request->nis),
                'level' => 'Siswa'
            ]);

            $user->siswa()->create($attr);

            DB::commit();

            return redirect()->route('siswa.index')->with('success', 'Siswa berhasil ditambahkan');
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->with('error', $th->getMessage());
        }
    }

    public function show(Siswa $siswa)
    {
        return view('siswa.show', compact('siswa'));
    }

    public function edit(Siswa $siswa)
    {
        return view('siswa.edit', compact('siswa'));
    }

    public function update(Request $request, Siswa $siswa)
    {
        $attr = $request->validate([
            'nis' => 'required|unique:siswas,nis,' . $siswa->id,
            'nama' => 'required',
            'kelas' => 'required'
        ]);

        try {
            DB::beginTransaction();

            $user = User::find($siswa->user_id);

            $user->update([
                'username' => $request->nis,
                'name' => $request->nama,
                'password' => bcrypt($request->nis),
                'level' => 'Siswa'
            ]);

            $user->siswa()->update($attr);

            DB::commit();

            return redirect()->route('siswa.index')->with('success', 'Siswa berhasil diupdate');
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->with('error', $th->getMessage());
        }
    }

    public function destroy(Siswa $siswa)
    {
        try {
            DB::beginTransaction();

            $siswa->user()->delete();
            $siswa->delete();

            DB::commit();

            return redirect()->route('siswa.index')->with('success', 'Siswa berhasil didelete');
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->with('error', $th->getMessage());
        }
    }

    public function nilai()
    {
        $siswa = Siswa::get();

        return view('siswa.nilai', compact('siswa'));
    }

    public function reset(Siswa $siswa)
    {
        $siswa->questions()->detach();

        return back()->with('success', 'Reset nilai siswa berhasil');
    }
}

resources/views/siswa/create.blade.php
@extends('layouts.master', ['title' => 'Tambah Siswa'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary card-outline">
            <div class="card-body">
                <form action="{{ route('siswa.store') }}" method="post">
                    @csrf

                    @include('siswa.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')

@endpush

resources/views/siswa/edit.blade.php
@extends('layouts.master', ['title' => 'Edit Siswa'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary card-outline">
            <div class="card-body">
                <form action="{{ route('siswa.update', $siswa->id) }}" method="post">
                    @method('PATCH')
                    @csrf

                    @include('siswa.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')

@endpush

resources/views/siswa/form.blade.php
<div class="form-group">
    <label for="nis">Nis</label>
    <input type="number" name="nis" id="nis" class="form-control" value="{{ $siswa->nis ?? old('nis') }}">

    @error('nis')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label for="nama">Nama</label>
    <input type="text" name="nama" id="nama" class="form-control" value="{{ $siswa->nama ?? old('nama') }}">

    @error('nama')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label for="kelas">Kelas</label>
    <input type="text" name="kelas" id="kelas" class="form-control" value="{{ $siswa->kelas ?? old('kelas') }}">

    @error('kelas')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <button type="submit" class="btn btn-primary">Submit</button>
</div>

resources/views/siswa/index.blade.php
@extends('layouts.master', ['title' => 'Data Siswa'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary card-outline">
            <div class="card-body">
                <a href="{{ route('siswa.create') }}" class="btn btn-primary mb-3">Tambah Siswa</a>

                <div class="table-responsive">
                    <table class="table table-bordered table-striped" id="data-table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nis</th>
                                <th>Nama</th>
                                <th>Kelas</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($siswa as $sw)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $sw->nis }}</td>
                                <td>{{ $sw->nama }}</td>
                                <td>{{ $sw->kelas }}</td>
                                <td>
                                    <a href="{{ route('siswa.edit', $sw->id) }}" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>

                                    <form action="{{ route('siswa.destroy', $sw->id) }}" method="post" class="d-inline">
                                        @method('DELETE')
                                        @csrf

                                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Hapus data Admin ?')"><i class="fas fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<script>
    $(document).ready(function() {
        $("#data-table").DataTable()
    })
</script>
@endpush

resources/views/siswa/nilai.blade.php
@extends('layouts.master', ['title' => 'Data Nilai Siswa'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary card-outline">
            <div class="card-body">

                <div class="table-responsive">
                    <table class="table table-bordered table-striped" id="data-table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nis</th>
                                <th>Nama</th>
                                <th>Nilai</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($siswa as $sw)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $sw->nis }}</td>
                                <td>{{ $sw->nama }}</td>
                                <td>{{ $sw->questions()->sum('nilai') }}</td>
                                <td>
                                    <a title="Detail" href="{{ route('siswa.show', $sw->id) }}" class="btn btn-sm btn-info"><i class="fas fa-eye"></i></a>
                                    <a title="Reset" href="{{ route('siswa.reset', $sw->id) }}" class="btn btn-sm btn-success" onclick="return confirm('Reset nilai siswa ?')"><i class="fas fa-sync"></i></a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<script>
    $(document).ready(function() {
        $("#data-table").DataTable()
    })
</script>
@endpush

resources/views/siswa/show.blade.php
@extends('layouts.master', ['title' => 'Detail Nilai Siswa'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary card-outline">
            <div class="card-body">

                <div class="table-responsive">
                    <table class="table table-bordered table-striped" id="data-table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Soal</th>
                                <th>Deskripsi</th>
                                <th>Jawaban</th>
                                <th>Nilai</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($siswa->questions as $question)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $question->soal }}</td>
                                <td>{{ $question->pivot->deskripsi }}</td>
                                <td>{{ $question->pivot->jawaban }}</td>
                                <td>{{ $question->pivot->nilai }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<script>
    $(document).ready(function() {
        $("#data-table").DataTable()
    })
</script>
@endpush